openapi: 3.0.0
info:
  title: API
  version: 1.0.0

servers:
  - url: https://api.example.com
    description: Production server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    VersionResponse:
      type: object
      properties:
        major:
          type: integer
        minor:
          type: integer
        patch:
          type: integer
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string

    TokenRequest:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string

    ConfirmAuthorizationRequest:
      type: object
      properties:
        email:
          type: string
        code:
          type: string

    QueueItemResponse:
      type: object
      properties:
        uid:
          type: string
        type:
          type: integer
        status:
          type: object
          properties:
            status:
              type: integer
              description: 0 - ожидает подтверждения, 1 - активная, 2 - отмененная
            statusFormatted:
              type: string
        info:
          $ref: "#/components/schemas/QueueResponseType"
        comment:
          type: string

    QueueResponseType:
      type: object
      discriminator:
        propertyName: responseType
        mapping:
          chat: "#/components/schemas/ChatSolutionResponse"
          document: "#/components/schemas/DocumentOrderResponse"
          timeSlot: "#/components/schemas/TimeSlotBookingResponse"
      properties:
        responseType:
          type: string
          enum: [chat, document, timeSlot]

    ChatSolutionResponse:
      allOf:
        - $ref: "#/components/schemas/QueueResponseType"
        - type: object
          properties:
            status:
              type: string
            isActive:
              type: boolean
            employee:
              $ref: "#/components/schemas/EmployeeResponse"

    DocumentOrderResponse:
      allOf:
        - $ref: "#/components/schemas/QueueResponseType"
        - type: object
          properties:
            type:
              type: integer
              description: |
                0 - другое
                1 - выписка с зачетной книжки
                2 - справка о периоде обучения
                3 - справка об обучении (для отчисленных)
                4 - справка-вызов (на период экз. лаб. сессии)

    TimeSlotBookingResponse:
      allOf:
        - $ref: "#/components/schemas/QueueResponseType"
        - type: object
          properties:
            status:
              type: string
              example: "Ваша позиция в очереди 14"
            timeFormatted:
              type: string
              example: "завтра, 14:15"
            employee:
              $ref: "#/components/schemas/EmployeeResponse"

    EmployeeResponse:
      type: object
      properties:
        uid:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        middleName:
          type: string
        deskNumber:
          type: string

paths:
  /version:
    get:
      tags:
        - info
      summary: Получает версию приложения
      operationId: getVersion
      responses:
        "200":
          description: Версия приложения
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResponse'

  /login:
    post:
      tags:
        - authorization
      summary: Авторизация пользователя
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        "200":
          description: Успешная авторизация
        "400":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /confirm:
    post:
      tags:
        - authorization
      summary: Подтверждение авторизации
      operationId: confirmAuthorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConfirmAuthorizationRequest"
      responses:
        "200":
          description: Успешное подтверждение
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /refresh:
    post:
      tags:
        - authorization
      security:
        - bearerAuth: []
      summary: Обновление токена
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenRequest"
      responses:
        "200":
          description: Токены обновлены
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /queue:
    get:
      tags:
        - queue
      security:
        - bearerAuth: []
      summary: Получает все текущие записи
      operationId: getQueue
      responses:
        "200":
          description: Список записей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/QueueItemResponse"
        "401":
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /queue/{uid}:
    get:
      tags:
        - queue
      security:
        - bearerAuth: []
      summary: Получает запись по UID
      operationId: getQueueItem
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Информация о записи
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QueueItemResponse"
        "401":
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /customer:
    get:
      tags:
        - customer
      security:
        - bearerAuth: []
      summary: Получает информацию о пользователе
      operationId: getCustomerInfo
      responses:
        "200":
          description: Информация о пользователе
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                  lastName:
                    type: string
                  firstName:
                    type: string
                  middleName:
                    type: string
                  citizenship:
                    type: string
                  course:
                    type: integer
                  groupNumber:
                    type: string
                  email:
                    type: string
        "401":
          description: Неавторизован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
